package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Activation generated by hbm2java
 */
@Entity
@Table(name="activation"
    ,catalog="greenwish"
)
public class Activation  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idactivation;
     private Participant participant;
     private Date datedesactivation;
     private Date dateactivation;

    public Activation() {
    }

	
    public Activation(Participant participant, Date datedesactivation) {
        this.participant = participant;
        this.datedesactivation = datedesactivation;
    }
    public Activation(Participant participant, Date datedesactivation, Date dateactivation) {
       this.participant = participant;
       this.datedesactivation = datedesactivation;
       this.dateactivation = dateactivation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDACTIVATION", unique=true, nullable=false)
    public Integer getIdactivation() {
        return this.idactivation;
    }
    
    public void setIdactivation(Integer idactivation) {
        this.idactivation = idactivation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPARTICIPANT", nullable=false)
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATEDESACTIVATION", nullable=false, length=19)
    public Date getDatedesactivation() {
        return this.datedesactivation;
    }
    
    public void setDatedesactivation(Date datedesactivation) {
        this.datedesactivation = datedesactivation;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATEACTIVATION", length=19)
    public Date getDateactivation() {
        return this.dateactivation;
    }
    
    public void setDateactivation(Date dateactivation) {
        this.dateactivation = dateactivation;
    }




}


