package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actualite generated by hbm2java
 */
@Entity
@Table(name="actualite"
    ,catalog="greenwish"
)
public class Actualite  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idactu;
     private String titre;
     private String texte;
     private String image;
     private Date datepublication;
     private Date datearchivage;
     private boolean actif;
     private List<Participant> participants = new ArrayList<>();

    public Actualite() {
    }

	
    public Actualite(Date datepublication, boolean actif) {
        this.datepublication = datepublication;
        this.actif = actif;
    }
    public Actualite(String titre, String texte, String image, Date datepublication, Date datearchivage, boolean actif, List<Participant> participants) {
       this.titre = titre;
       this.texte = texte;
       this.image = image;
       this.datepublication = datepublication;
       this.datearchivage = datearchivage;
       this.actif = actif;
       this.participants = participants;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDACTU", unique=true, nullable=false)
    public Integer getIdactu() {
        return this.idactu;
    }
    
    public void setIdactu(Integer idactu) {
        this.idactu = idactu;
    }

    
    @Column(name="TITRE", length=200)
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }

    
    @Column(name="TEXTE", length=5000)
    public String getTexte() {
        return this.texte;
    }
    
    public void setTexte(String texte) {
        this.texte = texte;
    }

    
    @Column(name="IMAGE", length=150)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATEPUBLICATION", nullable=false, length=19)
    public Date getDatepublication() {
        return this.datepublication;
    }
    
    public void setDatepublication(Date datepublication) {
        this.datepublication = datepublication;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATEARCHIVAGE", length=19)
    public Date getDatearchivage() {
        return this.datearchivage;
    }
    
    public void setDatearchivage(Date datearchivage) {
        this.datearchivage = datearchivage;
    }

    
    @Column(name="ACTIF", nullable=false)
    public boolean isActif() {
        return this.actif;
    }
    
    public void setActif(boolean actif) {
        this.actif = actif;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="actualites")
    public List<Participant> getParticipants() {
        return this.participants;
    }
    
    public void setParticipants(List<Participant> participants) {
        this.participants = participants;
    }




}


