package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name="categorie"
    ,catalog="greenwish"
)
public class Categorie  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idcategorie;
     private Domaine domaine;
     private String intitule;
     private List<Souscategorie> souscategories = new ArrayList<>();
     private List<Objet>objets = new ArrayList<>();

    public Categorie() {
    }

	
    public Categorie(Domaine domaine, String intitule) {
        this.domaine = domaine;
        this.intitule = intitule;
    }
    public Categorie(Domaine domaine, String intitule, List<Souscategorie> souscategories) {
       this.domaine = domaine;
       this.intitule = intitule;
       this.souscategories = souscategories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDCATEGORIE", unique=true, nullable=false)
    public Integer getIdcategorie() {
        return this.idcategorie;
    }
    
    public void setIdcategorie(Integer idcategorie) {
        this.idcategorie = idcategorie;
    }
    
    @OneToMany( mappedBy="categorie")
    public List<Objet> getObjets() {
        return this.objets;
    }
    
    public void setObjets(List<Objet> objets) {
        this.objets = objets;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDDOMAINE", nullable=false)
    public Domaine getDomaine() {
        return this.domaine;
    }
    
    public void setDomaine(Domaine domaine) {
        this.domaine = domaine;
    }

    
    @Column(name="INTITULE", nullable=false, length=150)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categorie")
    public List<Souscategorie> getSouscategories() {
        return this.souscategories;
    }
    
    public void setSouscategories(List<Souscategorie> souscategories) {
        this.souscategories = souscategories;
    }




}


