package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Disponibilite generated by hbm2java
 */
@Entity
@Table(name = "disponibilite", catalog = "greenwish")
public class Disponibilite implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private Integer iddispo;
	private Participant participant;
	private List<Participant> participants = new ArrayList<>();
	private List<Jour> jours = new ArrayList<>();

	public Disponibilite() {
	}

	public Disponibilite(Participant participant) {
		this.participant = participant;
	}

	public Disponibilite(Participant participant, List<Participant> participants, List<Jour> jours) {
		this.participant = participant;
		this.participants = participants;
		this.jours = jours;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDDISPO", unique = true, nullable = false)
	public Integer getIddispo() {
		return this.iddispo;
	}

	public void setIddispo(Integer iddispo) {
		this.iddispo = iddispo;
	}

	@ManyToOne
	@JoinColumn(name = "IDPARTICIPANT", nullable = false)
	public Participant getParticipant() {
		return this.participant;
	}

	public void setParticipant(Participant participant) {
		this.participant = participant;
	}

	@OneToMany(mappedBy = "disponibilite")
	public List<Participant> getParticipants() {
		return this.participants;
	}

	public void setParticipants(List<Participant> participants) {
		this.participants = participants;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "disponibilite", cascade = CascadeType.ALL)
	public List<Jour> getJours() {
		return this.jours;
	}

	public void setJours(List<Jour> jours) {
		this.jours = jours;
	}

}
