package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Favoris generated by hbm2java
 */
@Entity
@Table(name="favoris"
    ,catalog="greenwish"
)
public class Favoris  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idfavoris;
     private Objet objet;
     private List<Participant> participants = new ArrayList<>();

    public Favoris() {
    }

	
    public Favoris(Objet objet) {
        this.objet = objet;
    }
    public Favoris(Objet objet, List<Participant> participants) {
       this.objet = objet;
       this.participants = participants;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDFAVORIS", unique=true, nullable=false)
    public Integer getIdfavoris() {
        return this.idfavoris;
    }
    
    public void setIdfavoris(Integer idfavoris) {
        this.idfavoris = idfavoris;
    }

@ManyToOne
    @JoinColumn(name="IDOBJET", nullable=false)
    public Objet getObjet() {
        return this.objet;
    }
    
    public void setObjet(Objet objet) {
        this.objet = objet;
    }

@ManyToMany(mappedBy="favoris")
    public List<Participant> getParticipants() {
        return this.participants;
    }
    
    public void setParticipants(List<Participant> participants) {
        this.participants = participants;
    }




}


