package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Frequencenotif generated by hbm2java
 */
@Entity
@Table(name="frequencenotif"
    ,catalog="greenwish"
)
public class Frequencenotif  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idfrequence;
     private int frequence;
     private List<Reglage> reglages = new ArrayList<>();

    public Frequencenotif() {
    }

	
    public Frequencenotif(int frequence) {
        this.frequence = frequence;
    }
    public Frequencenotif(int frequence, List<Reglage> reglages) {
       this.frequence = frequence;
       this.reglages = reglages;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDFREQUENCE", unique=true, nullable=false)
    public Integer getIdfrequence() {
        return this.idfrequence;
    }
    
    public void setIdfrequence(Integer idfrequence) {
        this.idfrequence = idfrequence;
    }

    
    @Column(name="FREQUENCE", nullable=false)
    public int getFrequence() {
        return this.frequence;
    }
    
    public void setFrequence(int frequence) {
        this.frequence = frequence;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="frequencenotif")
    public List<Reglage> getReglages() {
        return this.reglages;
    }
    
    public void setReglages(List<Reglage> reglages) {
        this.reglages = reglages;
    }




}


