package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Horaire generated by hbm2java
 */
@Entity
@Table(name="horaire"
    ,catalog="greenwish"
)
public class Horaire  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idhoraire;
     private Jour jour;
     private Date heuredebut;
     private Date heurefin;

    public Horaire() {
    }

    public Horaire(Jour jour, Date heuredebut, Date heurefin) {
       this.jour = jour;
       this.heuredebut = heuredebut;
       this.heurefin = heurefin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDHORAIRE", unique=true, nullable=false)
    public Integer getIdhoraire() {
        return this.idhoraire;
    }
    
    public void setIdhoraire(Integer idhoraire) {
        this.idhoraire = idhoraire;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDJOUR", nullable=false)
    public Jour getJour() {
        return this.jour;
    }
    
    public void setJour(Jour jour) {
        this.jour = jour;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="HEUREDEBUT", nullable=false, length=19)
    public Date getHeuredebut() {
        return this.heuredebut;
    }
    
    public void setHeuredebut(Date heuredebut) {
        this.heuredebut = heuredebut;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="HEUREFIN", nullable=false, length=19)
    public Date getHeurefin() {
        return this.heurefin;
    }
    
    public void setHeurefin(Date heurefin) {
        this.heurefin = heurefin;
    }




}


