package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inscription generated by hbm2java
 */
@Entity
@Table(name="inscription"
    ,catalog="greenwish"
)
public class Inscription  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idinscription;
     private Participant participant;
     private Date dateinscription;
     private Date datedesinscription;

    public Inscription() {
    }

	
    public Inscription(Participant participant, Date dateinscription) {
        this.participant = participant;
        this.dateinscription = dateinscription;
    }
    public Inscription(Participant participant, Date dateinscription, Date datedesinscription) {
       this.participant = participant;
       this.dateinscription = dateinscription;
       this.datedesinscription = datedesinscription;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDINSCRIPTION", unique=true, nullable=false)
    public Integer getIdinscription() {
        return this.idinscription;
    }
    
    public void setIdinscription(Integer idinscription) {
        this.idinscription = idinscription;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPARTICIPANT", nullable=false)
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATEINSCRIPTION", nullable=false, length=19)
    public Date getDateinscription() {
        return this.dateinscription;
    }
    
    public void setDateinscription(Date dateinscription) {
        this.dateinscription = dateinscription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATEDESINSCRIPTION", length=19)
    public Date getDatedesinscription() {
        return this.datedesinscription;
    }
    
    public void setDatedesinscription(Date datedesinscription) {
        this.datedesinscription = datedesinscription;
    }




}


