package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ListeProposition generated by hbm2java
 */
@Entity
@Table(name="liste_proposition"
    ,catalog="greenwish"
)
public class ListeProposition  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idlisteobjet;
     private Participant participant;
     private String nom;
     private boolean actif;
     private List<Objet> objets = new ArrayList<>();

    public ListeProposition() {
    }

	
    public ListeProposition(Participant participant, String nom, boolean actif) {
        this.participant = participant;
        this.nom = nom;
        this.actif = actif;
    }
    public ListeProposition(Participant participant, String nom, boolean actif, List<Objet> objets) {
       this.participant = participant;
       this.nom = nom;
       this.actif = actif;
       this.objets = objets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDLISTEOBJET", unique=true, nullable=false)
    public Integer getIdlisteobjet() {
        return this.idlisteobjet;
    }
    
    public void setIdlisteobjet(Integer idlisteobjet) {
        this.idlisteobjet = idlisteobjet;
    }

@ManyToOne
    @JoinColumn(name="IDPARTICIPANT", nullable=false)
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }

    
    @Column(name="NOM", nullable=false, length=100)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="ACTIF", nullable=false, columnDefinition = "TINYINT(1)")
    public boolean isActif() {
        return this.actif;
    }
    
    public void setActif(boolean actif) {
        this.actif = actif;
    }

@OneToMany(mappedBy="listeProposition")
    public List<Objet> getObjets() {
        return this.objets;
    }
    
    public void setObjets(List<Objet> objets) {
        this.objets = objets;
    }




}


