package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Litige generated by hbm2java
 */
@Entity
@Table(name="litige"
    ,catalog="greenwish"
)
public class Litige  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idlitige;
     private Echange echange;
     private String motif;
     private String motifreceveur;
     private boolean resolu;
     private List<Echange> echanges = new ArrayList<>();

    public Litige() {
    }

	
    public Litige(Echange echange, String motif, String motifreceveur, boolean resolu) {
        this.echange = echange;
        this.motif = motif;
        this.motifreceveur = motifreceveur;
        this.resolu = resolu;
    }
    public Litige(Echange echange, String motif, String motifreceveur, boolean resolu, List<Echange> echanges) {
       this.echange = echange;
       this.motif = motif;
       this.motifreceveur = motifreceveur;
       this.resolu = resolu;
       this.echanges = echanges;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDLITIGE", unique=true, nullable=false)
    public Integer getIdlitige() {
        return this.idlitige;
    }
    
    public void setIdlitige(Integer idlitige) {
        this.idlitige = idlitige;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDECHANGE", nullable=false)
    public Echange getEchange() {
        return this.echange;
    }
    
    public void setEchange(Echange echange) {
        this.echange = echange;
    }

    
    @Column(name="MOTIF", nullable=false, length=250)
    public String getMotif() {
        return this.motif;
    }
    
    public void setMotif(String motif) {
        this.motif = motif;
    }

    
    @Column(name="MOTIFRECEVEUR", nullable=false, length=100)
    public String getMotifreceveur() {
        return this.motifreceveur;
    }
    
    public void setMotifreceveur(String motifreceveur) {
        this.motifreceveur = motifreceveur;
    }

    
    @Column(name="RESOLU", nullable=false, columnDefinition = "TINYINT(1)")
    public boolean isResolu() {
        return this.resolu;
    }
    
    public void setResolu(boolean resolu) {
        this.resolu = resolu;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="litige")
    public List<Echange> getEchanges() {
        return this.echanges;
    }
    
    public void setEchanges(List<Echange> echanges) {
        this.echanges = echanges;
    }




}


