package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Prioriterecherche generated by hbm2java
 */
@Entity
@Table(name="prioriterecherche"
    ,catalog="greenwish"
)
public class Prioriterecherche  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idpriorite;
     private String priorite;
     private List<Reglage> reglages = new ArrayList<>();

    public Prioriterecherche() {
    }

	
    public Prioriterecherche(String priorite) {
        this.priorite = priorite;
    }
    public Prioriterecherche(String priorite, List<Reglage> reglages) {
       this.priorite = priorite;
       this.reglages = reglages;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDPRIORITE", unique=true, nullable=false)
    public Integer getIdpriorite() {
        return this.idpriorite;
    }
    
    public void setIdpriorite(Integer idpriorite) {
        this.idpriorite = idpriorite;
    }

    
    @Column(name="PRIORITE", nullable=false, length=200)
    public String getPriorite() {
        return this.priorite;
    }
    
    public void setPriorite(String priorite) {
        this.priorite = priorite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prioriterecherche")
    public List<Reglage> getReglages() {
        return this.reglages;
    }
    
    public void setReglages(List<Reglage> reglages) {
        this.reglages = reglages;
    }




}


