package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Refus generated by hbm2java
 */
@Entity
@Table(name="refus"
    ,catalog="greenwish"
)
public class Refus  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idrefus;
     private String motif;
     private List<Echange> echanges = new ArrayList<>();

    public Refus() {
    }

	
    public Refus(String motif) {
        this.motif = motif;
    }
    public Refus(String motif, List<Echange> echanges) {
       this.motif = motif;
       this.echanges = echanges;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDREFUS", unique=true, nullable=false)
    public Integer getIdrefus() {
        return this.idrefus;
    }
    
    public void setIdrefus(Integer idrefus) {
        this.idrefus = idrefus;
    }

    
    @Column(name="MOTIF", nullable=false, length=250)
    public String getMotif() {
        return this.motif;
    }
    
    public void setMotif(String motif) {
        this.motif = motif;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="refuses")
    public List<Echange> getEchanges() {
        return this.echanges;
    }
    
    public void setEchanges(List<Echange> echanges) {
        this.echanges = echanges;
    }




}


