package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Reglage generated by hbm2java
 */
@Entity
@Table(name="reglage"
    ,catalog="greenwish"
)
public class Reglage  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idreglage;
     private Frequencenotif frequencenotif;
     private Participant participant;
     private Prioriterecherche prioriterecherche;
     private Taillepolice taillepolice;
     private Theme theme;
     private List<Participant> participants = new ArrayList<>();

    public Reglage() {
    }

	
    public Reglage(Participant participant) {
        this.participant = participant;
    }
    public Reglage(Frequencenotif frequencenotif, Participant participant, Prioriterecherche prioriterecherche, Taillepolice taillepolice, Theme theme, List<Participant> participants) {
       this.frequencenotif = frequencenotif;
       this.participant = participant;
       this.prioriterecherche = prioriterecherche;
       this.taillepolice = taillepolice;
       this.theme = theme;
       this.participants = participants;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDREGLAGE", unique=true, nullable=false)
    public Integer getIdreglage() {
        return this.idreglage;
    }
    
    public void setIdreglage(Integer idreglage) {
        this.idreglage = idreglage;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFREQUENCE")
    public Frequencenotif getFrequencenotif() {
        return this.frequencenotif;
    }
    
    public void setFrequencenotif(Frequencenotif frequencenotif) {
        this.frequencenotif = frequencenotif;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPARTICIPANT", nullable=false)
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPRIORITE")
    public Prioriterecherche getPrioriterecherche() {
        return this.prioriterecherche;
    }
    
    public void setPrioriterecherche(Prioriterecherche prioriterecherche) {
        this.prioriterecherche = prioriterecherche;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTAILLEPOLICE")
    public Taillepolice getTaillepolice() {
        return this.taillepolice;
    }
    
    public void setTaillepolice(Taillepolice taillepolice) {
        this.taillepolice = taillepolice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTHEME")
    public Theme getTheme() {
        return this.theme;
    }
    
    public void setTheme(Theme theme) {
        this.theme = theme;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="reglage")
    public List<Participant> getParticipants() {
        return this.participants;
    }
    
    public void setParticipants(List<Participant> participants) {
        this.participants = participants;
    }




}


