package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Souhait generated by hbm2java
 */
@Entity
@Table(name="souhait"
    ,catalog="greenwish"
)
public class Souhait  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idsouhait;
     private Domaine domaine;
     private Participant participant;
     private TrancheAge trancheAge;
     private String intitule;
     private Integer valeur;
     private Long distance;

    public Souhait() {
    }

	
    public Souhait(Participant participant) {
        this.participant = participant;
    }
    public Souhait(Domaine domaine, Participant participant, TrancheAge trancheAge, String intitule, Integer valeur, Long distance) {
       this.domaine = domaine;
       this.participant = participant;
       this.trancheAge = trancheAge;
       this.intitule = intitule;
       this.valeur = valeur;
       this.distance = distance;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDSOUHAIT", unique=true, nullable=false)
    public Integer getIdsouhait() {
        return this.idsouhait;
    }
    
    public void setIdsouhait(Integer idsouhait) {
        this.idsouhait = idsouhait;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDDOMAINE")
    public Domaine getDomaine() {
        return this.domaine;
    }
    
    public void setDomaine(Domaine domaine) {
        this.domaine = domaine;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPARTICIPANT", nullable=false)
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDAGE")
    public TrancheAge getTrancheAge() {
        return this.trancheAge;
    }
    
    public void setTrancheAge(TrancheAge trancheAge) {
        this.trancheAge = trancheAge;
    }

    
    @Column(name="INTITULE", length=150)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

    
    @Column(name="VALEUR")
    public Integer getValeur() {
        return this.valeur;
    }
    
    public void setValeur(Integer valeur) {
        this.valeur = valeur;
    }

    
    @Column(name="DISTANCE", precision=10, scale=0)
    public Long getDistance() {
        return this.distance;
    }
    
    public void setDistance(Long distance) {
        this.distance = distance;
    }




}


