package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Souscategorie generated by hbm2java
 */
@Entity
@Table(name="souscategorie"
    ,catalog="greenwish"
)
public class Souscategorie  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idsouscategorie;
     private Categorie categorie;
     private String intitule;
     private List<Objet> objets = new ArrayList<>();

    public Souscategorie() {
    }

    public Souscategorie(Categorie categorie, String intitule) {
       this.categorie = categorie;
       this.intitule = intitule;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDSOUSCATEGORIE", unique=true, nullable=false)
    public Integer getIdsouscategorie() {
        return this.idsouscategorie;
    }
    
    public void setIdsouscategorie(Integer idsouscategorie) {
        this.idsouscategorie = idsouscategorie;
    }
    
    @OneToMany(mappedBy="souscategorie")
    public List<Objet> getObjets() {
        return this.objets;
    }
    
    public void setObjets(List<Objet> objets) {
        this.objets = objets;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCATEGORIE", nullable=false)
    public Categorie getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(Categorie categorie) {
        this.categorie = categorie;
    }

    
    @Column(name="INTITULE", nullable=false, length=150)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }




}


