package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Statistique generated by hbm2java
 */
@Entity
@Table(name="statistique"
    ,catalog="greenwish"
)
public class Statistique  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idstat;
     private boolean actif;
     private String code;
     private List<Participant> participants = new ArrayList<>();

    public Statistique() {
    }

	
    public Statistique(boolean actif, String code) {
        this.actif = actif;
        this.code = code;
    }
    public Statistique(boolean actif, String code, List<Participant> participants) {
       this.actif = actif;
       this.code = code;
       this.participants = participants;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDSTAT", unique=true, nullable=false)
    public Integer getIdstat() {
        return this.idstat;
    }
    
    public void setIdstat(Integer idstat) {
        this.idstat = idstat;
    }

    
    @Column(name="ACTIF", nullable=false)
    public boolean isActif() {
        return this.actif;
    }
    
    public void setActif(boolean actif) {
        this.actif = actif;
    }

    
    @Column(name="CODE", nullable=false, length=2048)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="defini", catalog="greenwish", joinColumns = { 
        @JoinColumn(name="IDSTAT", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="IDPARTICIPANT", nullable=false, updatable=false) })
    public List<Participant> getParticipants() {
        return this.participants;
    }
    
    public void setParticipants(List<Participant> participants) {
        this.participants = participants;
    }




}


