package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Taillepolice generated by hbm2java
 */
@Entity
@Table(name="taillepolice"
    ,catalog="greenwish"
)
public class Taillepolice  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idtaillepolice;
     private String taillepolice;
     private List<Reglage> reglages = new ArrayList<>();

    public Taillepolice() {
    }

	
    public Taillepolice(String taillepolice) {
        this.taillepolice = taillepolice;
    }
    public Taillepolice(String taillepolice, List<Reglage> reglages) {
       this.taillepolice = taillepolice;
       this.reglages = reglages;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDTAILLEPOLICE", unique=true, nullable=false)
    public Integer getIdtaillepolice() {
        return this.idtaillepolice;
    }
    
    public void setIdtaillepolice(Integer idtaillepolice) {
        this.idtaillepolice = idtaillepolice;
    }

    
    @Column(name="TAILLEPOLICE", nullable=false, length=150)
    public String getTaillepolice() {
        return this.taillepolice;
    }
    
    public void setTaillepolice(String taillepolice) {
        this.taillepolice = taillepolice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taillepolice")
    public List<Reglage> getReglages() {
        return this.reglages;
    }
    
    public void setReglages(List<Reglage> reglages) {
        this.reglages = reglages;
    }




}


