package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Theme generated by hbm2java
 */
@Entity
@Table(name="theme"
    ,catalog="greenwish"
)
public class Theme  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idtheme;
     private String theme;
     private List<Reglage> reglages = new ArrayList<>();

    public Theme() {
    }

	
    public Theme(String theme) {
        this.theme = theme;
    }
    public Theme(String theme, List<Reglage> reglages) {
       this.theme = theme;
       this.reglages = reglages;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDTHEME", unique=true, nullable=false)
    public Integer getIdtheme() {
        return this.idtheme;
    }
    
    public void setIdtheme(Integer idtheme) {
        this.idtheme = idtheme;
    }

    
    @Column(name="THEME", nullable=false, length=150)
    public String getTheme() {
        return this.theme;
    }
    
    public void setTheme(String theme) {
        this.theme = theme;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="theme")
    public List<Reglage> getReglages() {
        return this.reglages;
    }
    
    public void setReglages(List<Reglage> reglages) {
        this.reglages = reglages;
    }




}


