package fr.afcepf.ai100.g3;
// Generated 28 avr. 2017 11:29:33 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ville generated by hbm2java
 */
@Entity
@Table(name="ville"
    ,catalog="greenwish"
)
public class Ville  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idville;
     private String ville;
     private String codePostal;
     private List<Participant> participants = new ArrayList<>();
     private List<Rdv> rdvs = new ArrayList<>();

    public Ville() {
    }

	
    public Ville(String ville, String codePostal) {
        this.ville = ville;
        this.codePostal = codePostal;
    }
    public Ville(String ville, String codePostal, List<Participant> participants, List<Rdv> rdvs) {
       this.ville = ville;
       this.codePostal = codePostal;
       this.participants = participants;
       this.rdvs = rdvs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDVILLE", unique=true, nullable=false)
    public Integer getIdville() {
        return this.idville;
    }
    
    public void setIdville(Integer idville) {
        this.idville = idville;
    }

    
    @Column(name="VILLE", nullable=false, length=200)
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }

    
    @Column(name="CODE_POSTAL", nullable=false, length=50)
    public String getCodePostal() {
        return this.codePostal;
    }
    
    public void setCodePostal(String codePostal) {
        this.codePostal = codePostal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ville")
    public List<Participant> getParticipants() {
        return this.participants;
    }
    
    public void setParticipants(List<Participant> participants) {
        this.participants = participants;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ville")
    public List<Rdv> getRdvs() {
        return this.rdvs;
    }
    
    public void setRdvs(List<Rdv> rdvs) {
        this.rdvs = rdvs;
    }




}


